services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/myapp
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
    volumes:
      - ./frontend/my-app:/my-app
    command: 'npm run dev'
    ports:
      - '8000:3000'
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
