name: 'Next.js CI'

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/my-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend/my-app
          npm install

      - name: Run ESLint
        run: |
          cd frontend/my-app
          npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run Prettier
        run: |
          cd frontend/my-app
          npx prettier --check .
